$Posts = @(
    @{ InputDate = '2009/04'; InputUrl='apology-to-raymond-chen.html'; OutputDate = '2009/04'; OutputFile='an-apology-to-raymond-chen.md' }
    @{ InputDate = '2009/05'; InputUrl='who-is-accu.html'; OutputDate = '2009/05'; OutputFile='who-is-the-accu.md' }
    @{ InputDate = '2009/05'; InputUrl='potted-history-of-my-windows-framework.html'; OutputDate = '2009/05'; OutputFile='potted-history-of-my-windows-framework.md' }
    @{ InputDate = '2009/05'; InputUrl='bcs-talk-introduction-to-f.html'; OutputDate = '2009/05'; OutputFile='bcs-talk-introduction-to-fsharp.md' }
    @{ InputDate = '2009/06'; InputUrl='visual-c-project-compare-v10-released.html'; OutputDate = '2009/06'; OutputFile='visual-cpp-project-compare-v1-released.md' }
    @{ InputDate = '2009/06'; InputUrl='class-generator-v20-released.html'; OutputDate = '2009/06'; OutputFile='class-generator-v2-released.md' }
    @{ InputDate = '2009/05'; InputUrl='building-visual-c-projects-from-command.html'; OutputDate = '2009/06'; OutputFile='building-visual-cpp-projects-from-the-command-line.md' }
    @{ InputDate = '2009/06'; InputUrl='visual-c-include-variable-and-useenv.html'; OutputDate = '2009/06'; OutputFile='visual-cpp-the-include-variable-and-the-useenv-switch.md' }
    @{ InputDate = '2009/06'; InputUrl='default-size-index-type-sizet-vs-int.html'; OutputDate = '2009/06'; OutputFile='the-default-size-and-index-type-size_t-vs-int.md' }
    @{ InputDate = '2009/06'; InputUrl='where-are-lite-editions-of-static-code.html'; OutputDate = '2009/06'; OutputFile='where-are-the-lite-editions-of-static-code-analysis-tools.md' }
    @{ InputDate = '2009/07'; InputUrl='gcc-for-visually-c-impaired.html'; OutputDate = '2009/07'; OutputFile='gcc-for-the-visually-cpp-impaired.md' }
    @{ InputDate = '2009/07'; InputUrl='using-visual-c-together-with-gcc-some.html'; OutputDate = '2009/07'; OutputFile='using-visual-cpp-together-with-gcc.md' }
    @{ InputDate = '2009/07'; InputUrl='my-first-published-articles.html'; OutputDate = '2009/07'; OutputFile='my-first-published-articles.md' }
    @{ InputDate = '2009/09'; InputUrl='going-back-to-work.html'; OutputDate = '2009/09'; OutputFile='going-back-to-work.md' }
    @{ InputDate = '2009/09'; InputUrl='perils-of-intellisense.html'; OutputDate = '2009/09'; OutputFile='the-perils-of-intellisense.md' }
    @{ InputDate = '2009/10'; InputUrl='we-dont-use-ie6-out-of-choice.html'; OutputDate = '2009/10'; OutputFile='we-dont-use-ie6-out-of-choice.md' }
    @{ InputDate = '2009/10'; InputUrl='dde-is-still-alive-kicking.html'; OutputDate = '2009/10'; OutputFile='dde-is-still-alive-and-kicking.md' }
    @{ InputDate = '2009/10'; InputUrl='stack-overflow-dev-days-london.html'; OutputDate = '2009/10'; OutputFile='stack-overflow-dev-days-london.md' }
    @{ InputDate = '2009/11'; InputUrl='chip-off-old-block.html'; OutputDate = '2009/11'; OutputFile='a-chip-off-the-old-block.md' }
    @{ InputDate = '2009/11'; InputUrl='happy-21st12th-anniversary.html'; OutputDate = '2009/11'; OutputFile='happy-21st-12th-anniversary.md' }
    @{ InputDate = '2009/11'; InputUrl='my-new-blogging-machine.html'; OutputDate = '2009/11'; OutputFile='my-new-blogging-machine.md' }
    @{ InputDate = '2009/11'; InputUrl='standard-method-name-verb-semantics.html'; OutputDate = '2009/11'; OutputFile='standard-method-name-verb-semantics.md' }
    @{ InputDate = '2009/11'; InputUrl='adjusting-to-cnet-ecosystem.html'; OutputDate = '2009/11'; OutputFile='adjusting-to-the-csharp-dotnet-ecosystem.md' }
    @{ InputDate = '2009/11'; InputUrl='c-c-ccli-context-switch-hell.html'; OutputDate = '2009/11'; OutputFile='csharp-cpp-cppcli-context-switch-hell.md' }
    @{ InputDate = '2009/11'; InputUrl='from-sourcesafe-to-clearcase-to.html'; OutputDate = '2009/11'; OutputFile='from-sourcesafe-to-clearcase-to-subversion.md' })
